/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as CleanupRouteImport } from './routes/cleanup'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'
import { Route as BookmarksIdRouteImport } from './routes/bookmarks.$id'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBookmarksIdRouteImport } from './routes/api/bookmarks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupRoute = CleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIdRoute = BookmarksIdRouteImport.update({
  id: '/bookmarks/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksIdRoute = ApiBookmarksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBookmarksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/cleanup': typeof CleanupRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/cleanup': typeof CleanupRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/cleanup': typeof CleanupRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/cleanup'
    | '/collections'
    | '/insights'
    | '/login'
    | '/settings'
    | '/share'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/cleanup'
    | '/collections'
    | '/insights'
    | '/login'
    | '/settings'
    | '/share'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/cleanup'
    | '/collections'
    | '/insights'
    | '/login'
    | '/settings'
    | '/share'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  CleanupRoute: typeof CleanupRoute
  CollectionsRoute: typeof CollectionsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  TrashRoute: typeof TrashRoute
  TwoFactorRoute: typeof TwoFactorRoute
  ApiBookmarksRoute: typeof ApiBookmarksRouteWithChildren
  ApiCollectionsRoute: typeof ApiCollectionsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiTagsRoute: typeof ApiTagsRoute
  ArchiveIdRoute: typeof ArchiveIdRoute
  BookmarksIdRoute: typeof BookmarksIdRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup': {
      id: '/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof CleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$id': {
      id: '/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof BookmarksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/$id': {
      id: '/api/bookmarks/$id'
      path: '/$id'
      fullPath: '/api/bookmarks/$id'
      preLoaderRoute: typeof ApiBookmarksIdRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
  }
}

interface ApiBookmarksRouteChildren {
  ApiBookmarksIdRoute: typeof ApiBookmarksIdRoute
}

const ApiBookmarksRouteChildren: ApiBookmarksRouteChildren = {
  ApiBookmarksIdRoute: ApiBookmarksIdRoute,
}

const ApiBookmarksRouteWithChildren = ApiBookmarksRoute._addFileChildren(
  ApiBookmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  CleanupRoute: CleanupRoute,
  CollectionsRoute: CollectionsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  TrashRoute: TrashRoute,
  TwoFactorRoute: TwoFactorRoute,
  ApiBookmarksRoute: ApiBookmarksRouteWithChildren,
  ApiCollectionsRoute: ApiCollectionsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiTagsRoute: ApiTagsRoute,
  ArchiveIdRoute: ArchiveIdRoute,
  BookmarksIdRoute: BookmarksIdRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
