/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHighlightsRouteImport } from './routes/api/highlights'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'
import { Route as BookmarksIdRouteImport } from './routes/bookmarks.$id'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBookmarksIdRouteImport } from './routes/api/bookmarks.$id'
import { Route as ApiBookmarksIdAskRouteImport } from './routes/api/bookmarks.$id.ask'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHighlightsRoute = ApiHighlightsRouteImport.update({
  id: '/api/highlights',
  path: '/api/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveRoute,
} as any)
const BookmarksIdRoute = BookmarksIdRouteImport.update({
  id: '/bookmarks/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksIdRoute = ApiBookmarksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBookmarksRoute,
} as any)
const ApiBookmarksIdAskRoute = ApiBookmarksIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ApiBookmarksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/highlights': typeof ApiHighlightsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/archive/': typeof ArchiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRouteWithChildren
  '/api/bookmarks/$id/ask': typeof ApiBookmarksIdAskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/highlights': typeof ApiHighlightsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/archive': typeof ArchiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRouteWithChildren
  '/api/bookmarks/$id/ask': typeof ApiBookmarksIdAskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/collections': typeof CollectionsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
  '/two-factor': typeof TwoFactorRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/collections': typeof ApiCollectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/highlights': typeof ApiHighlightsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/s/$token': typeof STokenRoute
  '/archive/': typeof ArchiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/$id': typeof ApiBookmarksIdRouteWithChildren
  '/api/bookmarks/$id/ask': typeof ApiBookmarksIdAskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/collections'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/share'
    | '/tags'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/highlights'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/archive/'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
    | '/api/bookmarks/$id/ask'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/collections'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/share'
    | '/tags'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/highlights'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/archive'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
    | '/api/bookmarks/$id/ask'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/collections'
    | '/insights'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/share'
    | '/tags'
    | '/trash'
    | '/two-factor'
    | '/api/bookmarks'
    | '/api/collections'
    | '/api/health'
    | '/api/highlights'
    | '/api/openapi.json'
    | '/api/tags'
    | '/archive/$id'
    | '/bookmarks/$id'
    | '/s/$token'
    | '/archive/'
    | '/api/auth/$'
    | '/api/bookmarks/$id'
    | '/api/bookmarks/$id/ask'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  CollectionsRoute: typeof CollectionsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  TagsRoute: typeof TagsRoute
  TrashRoute: typeof TrashRoute
  TwoFactorRoute: typeof TwoFactorRoute
  ApiBookmarksRoute: typeof ApiBookmarksRouteWithChildren
  ApiCollectionsRoute: typeof ApiCollectionsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHighlightsRoute: typeof ApiHighlightsRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiTagsRoute: typeof ApiTagsRoute
  BookmarksIdRoute: typeof BookmarksIdRoute
  STokenRoute: typeof STokenRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/highlights': {
      id: '/api/highlights'
      path: '/api/highlights'
      fullPath: '/api/highlights'
      preLoaderRoute: typeof ApiHighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/bookmarks/$id': {
      id: '/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof BookmarksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/$id': {
      id: '/api/bookmarks/$id'
      path: '/$id'
      fullPath: '/api/bookmarks/$id'
      preLoaderRoute: typeof ApiBookmarksIdRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
    '/api/bookmarks/$id/ask': {
      id: '/api/bookmarks/$id/ask'
      path: '/ask'
      fullPath: '/api/bookmarks/$id/ask'
      preLoaderRoute: typeof ApiBookmarksIdAskRouteImport
      parentRoute: typeof ApiBookmarksIdRoute
    }
  }
}

interface ApiBookmarksIdRouteChildren {
  ApiBookmarksIdAskRoute: typeof ApiBookmarksIdAskRoute
}

const ApiBookmarksIdRouteChildren: ApiBookmarksIdRouteChildren = {
  ApiBookmarksIdAskRoute: ApiBookmarksIdAskRoute,
}

const ApiBookmarksIdRouteWithChildren = ApiBookmarksIdRoute._addFileChildren(
  ApiBookmarksIdRouteChildren,
)

interface ApiBookmarksRouteChildren {
  ApiBookmarksIdRoute: typeof ApiBookmarksIdRouteWithChildren
}

const ApiBookmarksRouteChildren: ApiBookmarksRouteChildren = {
  ApiBookmarksIdRoute: ApiBookmarksIdRouteWithChildren,
}

const ApiBookmarksRouteWithChildren = ApiBookmarksRoute._addFileChildren(
  ApiBookmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  CollectionsRoute: CollectionsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  TagsRoute: TagsRoute,
  TrashRoute: TrashRoute,
  TwoFactorRoute: TwoFactorRoute,
  ApiBookmarksRoute: ApiBookmarksRouteWithChildren,
  ApiCollectionsRoute: ApiCollectionsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHighlightsRoute: ApiHighlightsRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiTagsRoute: ApiTagsRoute,
  BookmarksIdRoute: BookmarksIdRoute,
  STokenRoute: STokenRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
